name: NextJS Build

on: 
  push:
    branches: [ main ]

jobs:
  build-nextjs-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Nextjs App
        run: npm run build

      - name: Upload Build On Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: out/
